### PR TITLE
fix: explicitly use scope for translating validation errors

### LINKED ISSUE #154: Only display text when translations have been loaded properly
This library uses `translocoService.translate` to get the translation for the provided translation key. However, that doesn't always work properly for scoped translations (see the FAQ about failing translations: [link](https://jsverse.gitbook.io/transloco/faqs#why-does-the-translation-fail-when-using-translate-inside-ngoninit-but-work-with-the-structural-dire))

I propose that (a part of) the library is rewritten to take that into account, possibly by using the `translateSignal` syntax.

### PR DESCRIPTION
**Pull request by Tlepel**
This commit also moves to reactive components with signals over structural directives.

fix #154

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #154

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: projects/ngx-translation-validation/src/lib/ngx-tv-container/ngx-tv-container.component.ts [hunk 1]
```diff
@@ -8,25 +9,22 @@ import { HashMap, TranslocoDirective } from '@jsverse/transloco';
...
-    if (value !== this.componentText) {
-      this.componentHide = !value;
-      this.componentText = value || '';
-      this.cdr.detectChanges();
-    }
-  }
+  public parameters = input<HashMap | undefined>(undefined);
+  public text = input<string, string | null>('', {
+    transform: (v) => {
+      console.log('input', v);
```
Comment (TiesB) [inline projects/ngx-translation-validation/src/lib/ngx-tv-container/ngx-tv-container.component.ts:19]: Is this log supposed to stay?

File: projects/ngx-translation-validation/src/lib/ngx-tv-container/ngx-tv-container.component.ts [hunk 2]
```diff
@@ -8,25 +9,22 @@ import { HashMap, TranslocoDirective } from '@jsverse/transloco';
...
-  @Input() set parameters(value: Record<string, string | number> | undefined) {
-    this.componentParameters = value;
-    this.cdr.detectChanges();
-  }
+  protected translatedText = translateSignal(this.text, this.parameters, this.scope);
+  protected hide = computed(() => this.text().length > 0);
 
-  constructor(private cdr: ChangeDetectorRef) {}
+  constructor() {
+    effect(() => console.log('effect', this.text(), this.parameters()));
```
Comment (TiesB) [inline projects/ngx-translation-validation/src/lib/ngx-tv-container/ngx-tv-container.component.ts:28]: Same for this log

File: projects/ngx-translation-validation/src/lib/ngx-tv.module.ts [hunk 3]
```diff
@@ -22,14 +22,22 @@ import { NgxTvDirective } from './ngx-tv.directive';
 })
 export class NgxTvModule {
   static forRoot(config?: Partial<NgxTvConfig>): ModuleWithProviders<NgxTvModule> {
+    const translocoScope: ProviderScope = {
+      scope: getConfig(config).type,
+    };
+
     return {
       ngModule: NgxTvModule,
       providers: [
```
Comment (TiesB) [inline projects/ngx-translation-validation/src/lib/ngx-tv.module.ts:31]: Can this use the `provideNgxTv` method from `ngx-tv-providers.ts`?

**Comment by TiesB** [comment]
LGTM!

File: projects/ngx-translation-validation/src/lib/ngx-tv-container/ngx-tv-container.component.ts [hunk 4]
```diff
@@ -8,25 +9,15 @@ import { HashMap, TranslocoDirective } from '@jsverse/transloco';
...
+  });
 
-  @Input() set parameters(value: Record<string, string | number> | undefined) {
-    this.componentParameters = value;
-    this.cdr.detectChanges();
-  }
-
-  constructor(private cdr: ChangeDetectorRef) {}
+  protected translatedText = translateSignal(this.text, this.parameters, this.scope);
+  protected hide = computed(() => this.text().length > 0);
```
[the remark this answers is not in the document]
Comment (Tlepel) [reply projects/ngx-translation-validation/src/lib/ngx-tv-container/ngx-tv-container.component.ts]: Fixed 👍
